from django.urls import re_path
from . import views

urlpatterns = [
    re_path(r"^$", views.home, name="home"),
    re_path(r"^login/$", views.login, name="login"),
    re_path(r"^logout/$", views.logout, name="logout"),
    re_path(r"^department/list/", views.department_list, name="department_list"),
    re_path(r"^department/new", views.department_new, name="department_new"),
    re_path(r"^department/(?P<id>\d+)/edit/$", views.department_edit, name="department_edit"),
    re_path(r"^department/(?P<id>\d+)/delete/$", views.department_delete, name="department_delete"),
    re_path(r"^designation/list/", views.designation_list, name="designation_list"),
    re_path(r"^designation/new", views.designation_new, name="designation_new"),
    re_path(r"^designation/(?P<id>\d+)/edit/$", views.designation_edit, name="designation_edit"),
    re_path(r"^designation/(?P<id>\d+)/delete/$", views.designation_delete, name="designation_delete"),
    re_path(r"^evaluator/list/", views.evaluator_list, name="evaluator_list"),
    re_path(r"^evaluator/new", views.evaluator_new, name="evaluator_new"),
    re_path(r"^evaluator/(?P<id>\d+)/detail/$", views.evaluator_detail, name="evaluator_detail"),
    re_path(r"^evaluator/(?P<id>\d+)/edit/$", views.evaluator_edit, name="evaluator_edit"),
    re_path(r"^evaluator/(?P<id>\d+)/delete/$", views.evaluator_delete, name="evaluator_delete"),
    re_path(r"^employee/list/", views.employee_list, name="employee_list"),
    re_path(r"^employee/new", views.employee_new, name="employee_new"),
    re_path(r"^employee/(?P<id>\d+)/detail/$", views.employee_detail, name="employee_update"),
    re_path(r"^employee/(?P<id>\d+)/edit/$", views.employee_edit, name="employee_edit"),
    re_path(r"^employee/(?P<id>\d+)/delete/$", views.employee_delete, name="employee_delete"),
    re_path(r"^task/list/$", views.task_list, name="task_list"),
    re_path(r"^task/new$", views.task_new, name="task_new"),
    re_path(r"^task/(?P<id>\d+)/edit/$", views.task_edit, name="task_edit"),
    re_path(r"^task/(?P<id>\d+)/delete/$", views.task_delete, name="task_delete"),
    re_path(r"^task/(?P<id>\d+)/progress/new$", views.progress_new, name="progress_new"),
    re_path(r"^task/(?P<id>\d+)/progress/detail/$", views.progress_detail, name="progress_detail"),
    re_path(r"^evaluation/list/$", views.evaluation_list, name="evaluation_list"),
    re_path(r"^task/(?P<id>\d+)/evaluation/new$", views.evaluation_new, name="evaluation_new"),
    re_path(r"^task/(?P<id>\d+)/evaluation/detail/$", views.evaluation_detail, name="evaluation_detail"),
    re_path(r"^task/(?P<id>\d+)/evaluation/edit/$", views.evaluation_edit, name="evaluation_edit"),
    re_path(r"^task/(?P<id>\d+)/evaluation/delete/$", views.evaluation_delete, name="evaluation_delete"),
]