# Generated by Django 3.2.4 on 2021-07-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluator',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='evaluators/'),
        ),
        migrations.AlterField(
            model_name='regularuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='reg_users/'),
        ),
    ]
