# Generated by Django 3.2.4 on 2021-08-31 18:43

from django.db import migrations
from datetime import date
import random

TASKS = [
    [
        {
            "name": "Task number one",
            "description": "Complete task number one",
            "assigned_to": 4,
            "evaluator": 10,
            "status": "complete",
            "due_date": date(2021, 5, 11),
            "created": date(2021, 5, 5),
        },
        {
            "name": "Task number four",
            "description": "Complete task number four",
            "assigned_to": 4,
            "evaluator": 10,
            "status": "complete",
            "due_date": date(2021, 5, 28),
            "created": date(2021, 5, 18),
        },
        {
            "name": "Task number seven",
            "description": "Complete task number seven",
            "assigned_to": 4,
            "evaluator": 10,
            "status": "complete",
            "due_date": date(2021, 6, 11),
            "created": date(2021, 6, 5),
        },
        {
            "name": "Task number ten",
            "description": "Complete task number ten",
            "assigned_to": 4,
            "evaluator": 10,
            "status": "complete",
            "due_date": date(2021, 6, 28),
            "created": date(2021, 6, 18),
        },
        {
            "name": "Task number thirteen",
            "description": "Complete task number thirteen",
            "assigned_to": 4,
            "evaluator": 10,
            "status": "complete",
            "due_date": date(2021, 7, 11),
            "created": date(2021, 7, 5),
        },
        {
            "name": "Task number sixteen",
            "description": "Complete task number sixteen",
            "assigned_to": 4,
            "evaluator": 10,
            "status": "complete",
            "due_date": date(2021, 7, 28),
            "created": date(2021, 7, 18),
        },
        {
            "name": "Task number nineteen",
            "description": "Complete task number nineteen",
            "assigned_to": 4,
            "evaluator": 10,
            "status": "complete",
            "due_date": date(2021, 8, 11),
            "created": date(2021, 8, 5),
        },
        {
            "name": "Task number twenty two",
            "description": "Task number twenty two",
            "assigned_to": 4,
            "evaluator": 10,
            "status": "complete",
            "due_date": date(2021, 8, 28),
            "created": date(2021, 8, 18),
        },
    ],
    [
        {
            "name": "Task number two",
            "description": "Complete task number two",
            "assigned_to": 9,
            "evaluator": 12,
            "status": "complete",
            "due_date": date(2021, 5, 11),
            "created": date(2021, 5, 5),
        },
        {
            "name": "Task number five",
            "description": "Complete task number five",
            "assigned_to": 9,
            "evaluator": 12,
            "status": "complete",
            "due_date": date(2021, 5, 28),
            "created": date(2021, 5, 18),
        },
        {
            "name": "Task number eight",
            "description": "Complete task number eight",
            "assigned_to": 9,
            "evaluator": 12,
            "status": "complete",
            "due_date": date(2021, 6, 11),
            "created": date(2021, 6, 5),
        },
        {
            "name": "Task number eleven",
            "description": "Complete task number eleven",
            "assigned_to": 9,
            "evaluator": 12,
            "status": "complete",
            "due_date": date(2021, 6, 28),
            "created": date(2021, 6, 18),
        },
        {
            "name": "Task number fourteen",
            "description": "Complete task number fourteen",
            "assigned_to": 9,
            "evaluator": 12,
            "status": "complete",
            "due_date": date(2021, 7, 11),
            "created": date(2021, 7, 5),
        },
        {
            "name": "Task number seventeen",
            "description": "Complete task number seventeen",
            "assigned_to": 9,
            "evaluator": 12,
            "status": "complete",
            "due_date": date(2021, 7, 28),
            "created": date(2021, 7, 18),
        },
        {
            "name": "Task number twenty",
            "description": "Complete task number twenty",
            "assigned_to": 9,
            "evaluator": 12,
            "status": "complete",
            "due_date": date(2021, 8, 11),
            "created": date(2021, 8, 5),
        },
        {
            "name": "Task number twenty three",
            "description": "Task number twenty three",
            "assigned_to": 9,
            "evaluator": 12,
            "status": "complete",
            "due_date": date(2021, 8, 28),
            "created": date(2021, 8, 18),
        },
    ],
    [
        {
            "name": "Task number three",
            "description": "Complete task number three",
            "assigned_to": 10,
            "evaluator": 14,
            "status": "complete",
            "due_date": date(2021, 5, 11),
            "created": date(2021, 5, 5),
        },
        {
            "name": "Task number six",
            "description": "Complete task number six",
            "assigned_to": 10,
            "evaluator": 14,
            "status": "complete",
            "due_date": date(2021, 5, 28),
            "created": date(2021, 5, 18),
        },
        {
            "name": "Task number nine",
            "description": "Complete task number nine",
            "assigned_to": 10,
            "evaluator": 14,
            "status": "complete",
            "due_date": date(2021, 6, 11),
            "created": date(2021, 6, 5),
        },
        {
            "name": "Task number twelve",
            "description": "Complete task number twelve",
            "assigned_to": 10,
            "evaluator": 14,
            "status": "complete",
            "due_date": date(2021, 6, 28),
            "created": date(2021, 6, 18),
        },
        {
            "name": "Task number fifteen",
            "description": "Complete task number fifteen",
            "assigned_to": 10,
            "evaluator": 14,
            "status": "complete",
            "due_date": date(2021, 7, 11),
            "created": date(2021, 7, 5),
        },
        {
            "name": "Task number eighteen",
            "description": "Complete task number eighteen",
            "assigned_to": 10,
            "evaluator": 14,
            "status": "complete",
            "due_date": date(2021, 7, 28),
            "created": date(2021, 7, 18),
        },
        {
            "name": "Task number twenty one",
            "description": "Complete task number twenty one",
            "assigned_to": 10,
            "evaluator": 14,
            "status": "complete",
            "due_date": date(2021, 8, 11),
            "created": date(2021, 8, 5),
        },
        {
            "name": "Task number twenty four",
            "description": "Task number twenty four",
            "assigned_to": 10,
            "evaluator": 14,
            "status": "complete",
            "due_date": date(2021, 8, 28),
            "created": date(2021, 8, 18),
        },
    ]
]

PROGRESS = [
    [
        ("first progress", date(2021, 5, 7)),
        ("last progress", date(2021, 5, 10))
    ],
    [
        ("first progress", date(2021, 5, 21)),
        ("last progress", date(2021, 5, 26))
    ],
    [
        ("first progress", date(2021, 6, 7)),
        ("last progress", date(2021, 6, 10))
    ],
    [
        ("first progress", date(2021, 6, 21)),
        ("last progress", date(2021, 6, 26))
    ],
    [
        ("first progress", date(2021, 7, 7)),
        ("last progress", date(2021, 7, 10))
    ],
    [
        ("first progress", date(2021, 7, 21)),
        ("last progress", date(2021, 7, 26))
    ],
    [
        ("first progress", date(2021, 8, 7)),
        ("last progress", date(2021, 8, 10))
    ],
    [
        ("first progress", date(2021, 8, 21)),
        ("last progress", date(2021, 8, 26))
    ]
]

EVALUATION_DATES = [
    date(2021, 5, 10),
    date(2021, 5, 27),
    date(2021, 6, 10),
    date(2021, 6, 27),
    date(2021, 7, 10),
    date(2021, 7, 27),
    date(2021, 8, 10),
    date(2021, 8, 27),
]

def perf_averager(ratings):
    efficiency = ratings.efficiency
    timeliness = ratings.timeliness
    quality = ratings.quality
    accuracy = ratings.accuracy
    return (efficiency + timeliness + quality + accuracy) * 5


def add_task_data(apps, schema_editor):
    Task = apps.get_model("evaluator", "Task")
    Evaluator = apps.get_model("evaluator", "Evaluator")
    Employee = apps.get_model("evaluator", "Employee")
    Progress = apps.get_model("evaluator", "Progress")
    Evaluation = apps.get_model("evaluator", "Evaluation")
    Ratings = apps.get_model("evaluator", "Ratings")
    for task in TASKS:
        index = 0
        for task_data in task:
            task = Task.objects.create(
                name=task_data["name"],
                description=task_data["description"],
                assigned_to=Employee.objects.get(id=task_data["assigned_to"]),
                evaluator=Evaluator.objects.get(id=task_data["evaluator"]),
                status=task_data["status"],
                due_date=task_data["due_date"],
            )
            task.created = task_data["created"]
            task.save()
            for progress_descr, progress_date in PROGRESS[index]:
                progress = Progress.objects.create(
                    description=progress_descr,
                    task=task,
                    date_added=progress_date
                )
                progress.date_added = progress_date
                progress.save()
            ratings = Ratings(
                efficiency=random.randint(1, 5),
                timeliness=random.randint(1, 5),
                quality=random.randint(1, 5),
                accuracy=random.randint(1, 5),
            )
            ratings.performance_average = perf_averager(ratings)
            ratings.save()
            evaluation = Evaluation.objects.create(
                task=task,
                remarks="dummy evaluation remark",
                ratings=ratings
            )
            evaluation.date_evaluated = EVALUATION_DATES[index]
            evaluation.save()
            index +=1
    
def remove_task_data(apps, schema_editor):
    Task = apps.get_model("evaluator", "Task")
    for task in TASKS:
        for task_data in task:
            Task.objects.get(name=task_data["name"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0005_auto_20210804_0205'),
    ]

    operations = [
        migrations.RunPython(
            add_task_data,
            remove_task_data
        )
    ]
